/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.100
 * Generated at: 2025-03-18 07:45:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qualityControl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1741565182956L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Desktop/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_java/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Desktop/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_java/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/Users/admin/Desktop/Project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/project_java/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>품질관리</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css\\qualityControl.css\">\r\n");
      out.write("<script src=\"js\\qualityControl.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"myModal\" class=\"modal\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<span class=\"close\">&times;</span>\r\n");
      out.write("			<p>여기는 모달창 내용 영역입니다.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"warrap\">\r\n");
      out.write("		<div class=\"wkr\">\r\n");
      out.write("			<div class=\"wkrTop\">\r\n");
      out.write("				<div class=\"wkrwl\">실적 조회</div>\r\n");
      out.write("				<div>\r\n");
      out.write("					<form action=\"qualityControl\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" name=\"command\" value=\"search1\"> <input\r\n");
      out.write("							name=\"date\" type=\"date\" class=\"date2\" style=\"margin: 10px;\"\r\n");
      out.write("							id=\"date3\"\r\n");
      out.write("							value=\"");
      out.print(request.getParameter("date") != null ? request.getParameter("date") : "");
      out.write("\">\r\n");
      out.write("						<input type=\"submit\" class=\"btn1\" value=\"조회\">\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"wkrView\">\r\n");
      out.write("				<div class=\"indexBox\" id=\"index\">\r\n");
      out.write("					<div class=\"index\">\r\n");
      out.write("						<div>등록시간</div>\r\n");
      out.write("						<div>제품명</div>\r\n");
      out.write("						<div>수량</div>\r\n");
      out.write("						<div>코멘트</div>\r\n");
      out.write("						<div>등록인</div>\r\n");
      out.write("						<div>비고</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"perForm\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"bord\">\r\n");
      out.write("			<div class=\"inBord\">\r\n");
      out.write("				<div>검사완료율</div>\r\n");
      out.write("				<div>%</div>\r\n");
      out.write("				<div>(제품별)</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"inBord\">\r\n");
      out.write("				<div>불량률</div>\r\n");
      out.write("				<div>%</div>\r\n");
      out.write("				<div>(제품별)</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"box2\">\r\n");
      out.write("			<div class=\"left\">\r\n");
      out.write("				<div class=\"wp\">제품명</div>\r\n");
      out.write("				<div class=\"btn2B\">\r\n");
      out.write("					<button class=\"btn2\">제품 합격 / 불합격 기준</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<form method=\"post\" action=\"qualityControl\" class=\"right\"\r\n");
      out.write("				style=\"border: 1px solid rgb(199, 196, 196);\" id=\"formK\">\r\n");
      out.write("				<!-- form 여기있어요 -->\r\n");
      out.write("				<input type=\"hidden\" name=\"command\" value=\"insert\"> <input\r\n");
      out.write("					type=\"hidden\" name=\"performanceId\" class=\"performId\"\r\n");
      out.write("					id=\"performId1\">\r\n");
      out.write("				<div class=\"right\" style=\"width: 100%;\">\r\n");
      out.write("					<div class=\"rightTop\">\r\n");
      out.write("						<div class=\"wp2\">제품명</div>\r\n");
      out.write("						<input type=\"hidden\" name=\"wpvnaaud\" id=\"wpvnaaud\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"radio\" name=\"ra\" checked=\"checked\" class=\"rad\"\r\n");
      out.write("								value=\"합격\"> 합격 <input type=\"radio\" name=\"ra\" class=\"rad\"\r\n");
      out.write("								value=\"불합격\"> 불합격\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"datetime-local\" class=\"insertDate\" name=\"date\"\r\n");
      out.write("								style=\"font-size: 15px;\">\r\n");
      out.write("							<div>\r\n");
      out.write("								합격 갯수입력 : <input type=\"number\" class=\"myInput\" min=\"0\" max=\"100\"\r\n");
      out.write("									oninput=\"validity.valid||(value='')\" placeholder=\"0\"\r\n");
      out.write("									name=\"passPack\" id=\"passInput\"> pack\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								불합 개수입력 : <input type=\"number\" class=\"myInput\" min=\"0\" max=\"100\"\r\n");
      out.write("									oninput=\"validity.valid||(value='')\" placeholder=\"0\"\r\n");
      out.write("									name=\"failPack\" id=\"failInput\"> pack\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"insert\">\r\n");
      out.write("						<textarea placeholder=\"기타사항\" class=\"textBox\" rows=\"2\"\r\n");
      out.write("							name=\"comment\"></textarea>\r\n");
      out.write("						<input type=\"submit\" class=\"btn3\" value=\"등록\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"BB\">\r\n");
      out.write("						<div class=\"BB2 hide\">불합격 사유 :</div>\r\n");
      out.write("						<select class=\"dropBox hide\" name=\"failreason\" disabled>\r\n");
      out.write("							<option value=\"무게 미달\">무게 미달</option>\r\n");
      out.write("							<option value=\"외관 불량\">외관 불량</option>\r\n");
      out.write("							<option value=\"자재 불량\">자재 불량</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"box3\">\r\n");
      out.write("			<form action=\"qualityControl\" method=\"post\" class=\"box3\"\r\n");
      out.write("				id=\"searchForm\">\r\n");
      out.write("				<input type=\"hidden\" name=\"command\" value=\"search\">\r\n");
      out.write("				<div class=\"box3Top\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"text\" placeholder=\"제품명\" class=\"wp3\"\r\n");
      out.write("							name=\"productName\"\r\n");
      out.write("							value=\"");
      out.print(request.getParameter("productName") != null ? request.getParameter("productName") : "");
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"date2\">\r\n");
      out.write("						날짜 : <input type=\"datetime-local\" class=\"indate1\" name=\"startDate\"\r\n");
      out.write("							value=\"");
      out.print(request.getParameter("startDate") != null ? request.getParameter("startDate") : "");
      out.write("\">\r\n");
      out.write("						~ <input type=\"datetime-local\" class=\"indate2\" name=\"endDate\"\r\n");
      out.write("							value=\"");
      out.print(request.getParameter("endDate") != null ? request.getParameter("endDate") : "");
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						결과 : <select class=\"dropBox2\" name=\"result\">\r\n");
      out.write("							<option value=\"\"\r\n");
      out.write("								");
      out.print("전체".equals(request.getParameter("result")) ? "selected" : "");
      out.write(">전체</option>\r\n");
      out.write("							<option value=\"합격\"\r\n");
      out.write("								");
      out.print("합격".equals(request.getParameter("result")) ? "selected" : "");
      out.write(">합격</option>\r\n");
      out.write("							<option value=\"불합격\"\r\n");
      out.write("								");
      out.print("불합격".equals(request.getParameter("result")) ? "selected" : "");
      out.write(">불합격</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						불합격 사유 : <select class=\"dropBox2\" name=\"failreason\">\r\n");
      out.write("							<option value=\"\"\r\n");
      out.write("								");
      out.print("전체".equals(request.getParameter("failreason")) ? "selected" : "");
      out.write(">전체</option>\r\n");
      out.write("							<option value=\"무게 미달\"\r\n");
      out.write("								");
      out.print("무게 미달".equals(request.getParameter("failreason")) ? "selected" : "");
      out.write(">무게\r\n");
      out.write("								미달</option>\r\n");
      out.write("							<option value=\"외관 불량\"\r\n");
      out.write("								");
      out.print("외관 불량".equals(request.getParameter("failreason")) ? "selected" : "");
      out.write(">외관\r\n");
      out.write("								불량</option>\r\n");
      out.write("							<option value=\"자재 불량\"\r\n");
      out.write("								");
      out.print("자재 불량".equals(request.getParameter("failreason")) ? "selected" : "");
      out.write(">자재\r\n");
      out.write("								불량</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<input type=\"submit\" class=\"btn4\" value=\"검색\" id=\"searchbtn\">\r\n");
      out.write("						<button class=\"btn4\" id=\"reset\">초기화</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"dede\">\r\n");
      out.write("				<div class=\"index\" style=\"margin-left: 6px;\">\r\n");
      out.write("					<div>날짜</div>\r\n");
      out.write("					<div>제품명</div>\r\n");
      out.write("					<div>합격/불합격</div>\r\n");
      out.write("					<div>불합격 사유</div>\r\n");
      out.write("					<div>코멘트</div>\r\n");
      out.write("					<div>등록인</div>\r\n");
      out.write("					<div>비고</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"box3View\">\r\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("		// 실적 조회 박스에서 선택버튼 선택시 \r\n");
      out.write("		// performanceId\r\n");
      out.write("		const selectItem = document.querySelectorAll('.selectItem')\r\n");
      out.write("		for(let i = 0 ; i < selectItem.length ; i++){\r\n");
      out.write("			selectItem[i].addEventListener('click', (e)=>{\r\n");
      out.write("				\r\n");
      out.write("				const item  = document.querySelectorAll('.item')\r\n");
      out.write("				for(let j = 0 ; j < item.length ; j++){\r\n");
      out.write("			    	item[j].classList.remove('viewSelect');\r\n");
      out.write("				}\r\n");
      out.write("			    \r\n");
      out.write("			    e.target.parentNode.parentNode.classList.add('viewSelect');\r\n");
      out.write("				\r\n");
      out.write("				const idValue = e.target.parentNode.parentNode.querySelector('.performId').value;\r\n");
      out.write("				const idValue2 = e.target.parentNode.parentNode.querySelector('.productid').value;\r\n");
      out.write("			    document.querySelector('#wpvnaaud').value = idValue2;\r\n");
      out.write("			    document.querySelector('#performId1').value = idValue;\r\n");
      out.write("			    \r\n");
      out.write("			    document.querySelector('.wp').innerText = e.target.parentNode.parentNode.querySelector('.emdwp').innerText\r\n");
      out.write("			    document.querySelector('.wp2').innerText = e.target.parentNode.parentNode.querySelector('.emdwp').innerText\r\n");
      out.write("			    \r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		// 등록 버튼\r\n");
      out.write("		document.querySelector('.btn3').addEventListener('click', (e) => {\r\n");
      out.write("			\r\n");
      out.write("			e.preventDefault()\r\n");
      out.write("			\r\n");
      out.write("			const pass = document.querySelector('#passInput').value\r\n");
      out.write("			const fail = document.querySelector('#failInput').value\r\n");
      out.write("			\r\n");
      out.write("			if( document.querySelector('.wp2').innerText == \"제품명\" ){\r\n");
      out.write("				alert(\"제품이 선택되지않았습니다.\");\r\n");
      out.write("				return;\r\n");
      out.write("			} \r\n");
      out.write("			if ( pass == null || pass == \"\" || fail == null || fail == \"\" || (pass < 0 && pass < 100) || (fail < 0 && fail < 100) ) {\r\n");
      out.write("				alert(\"합격갯수 불합격갯수를 입력해주세요.\\n합격 : 0 ~ 100개\\n불합격 : 0~100개\")\r\n");
      out.write("				return;\r\n");
      out.write("			} else{\r\n");
      out.write("				alert(\"품질등록이 완료되었습니다.\");\r\n");
      out.write("				document.querySelector('#formK').submit();\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 수정버튼\r\n");
      out.write("		const modify = document.querySelectorAll('.modify')\r\n");
      out.write("		 for(let i = 0 ; i < modify.length ; i++){ \r\n");
      out.write("	 		modify[i].addEventListener('click', (e)=>{\r\n");
      out.write("				const view = e.target.parentNode.parentNode;\r\n");
      out.write("				const ControlId = view.querySelector('#qualityControlId').value\r\n");
      out.write("				const date = view.querySelector('#qualitydate').innerText\r\n");
      out.write("				const name = view.querySelector('#qualityName').innerText\r\n");
      out.write("				const result = view.querySelector('#qualityResult').innerText\r\n");
      out.write("				const failreason = view.querySelector('#qualityFailreason').innerText\r\n");
      out.write("				const comments = view.querySelector('#qualityComments').innerText\r\n");
      out.write("				const userId = view.querySelector('#qualityUserId').innerText\r\n");
      out.write("				\r\n");
      out.write("				view.innerHTML = \"\";\r\n");
      out.write("			       view.innerHTML += `\r\n");
      out.write("									<form method=\"post\" action=\"qualityControl\" class=\"dex item\">\r\n");
      out.write("							    	    <input type=\"hidden\" name=\"command\" value=\"update\">\r\n");
      out.write("							    	    <input type=\"hidden\" name=\"qualityControlId\" value=\"${ ControlId }\">\r\n");
      out.write("										<div class=\"dateB\" id=\"qualitydate\">\r\n");
      out.write("					    	  				<input type=\"datetime-local\" class=\"date1\" name=\"date22\" value=\"${date}\" style=\"font-size:10px\">\r\n");
      out.write("					       				</div>\r\n");
      out.write("										<div class=\"emdwp\" id=\"qualityName\">${name}</div>\r\n");
      out.write("										<div class=\"emdgkq\" id=\"qualityResult\">\r\n");
      out.write("												<select name=\"qualityResult22\" id=\"selectPass\" class=\"emdgkq\" style=\"font-size:12px\">\r\n");
      out.write("										            <option value=\"합격\">합격</option>\r\n");
      out.write("										            <option value=\"불합격\">불합격</option>\r\n");
      out.write("									           	</select></div>\r\n");
      out.write("										<div class=\"tkdb\" id=\"qualityFailreason\" style=\"display: flex; justify-content: center;\">\r\n");
      out.write("											<select class=\"dropBox\" name=\"failreason22\" style=\"font-size:12px\">\r\n");
      out.write("											<option value=\"\">없음</option>\r\n");
      out.write("											<option value=\"무게 미달\">무게 미달</option>\r\n");
      out.write("											<option value=\"외관 불량\">외관 불량</option>\r\n");
      out.write("											<option value=\"자재 불량\">자재 불량</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"text1\" id=\"qualityComments\"> <input type=\"text\" value=\"${comments}\" name=\"comment22\" style=\"font-size:12px\"></div>\r\n");
      out.write("										<div class=\"text1\" id=\"qualityUserId\">${userId}</div>\r\n");
      out.write("										<div\r\n");
      out.write("											style=\"display: flex; justify-content: center; align-items: center;\">\r\n");
      out.write("												<input type=\"submit\" name=\"tn\" value=\"완료\" id=\"Comple\"\r\n");
      out.write("													style=\"font-size: 12px; height: 25px;\">\r\n");
      out.write("											<button style=\"font-size: 12px; height: 25px;\" id=\"cancel\">취소</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("			                       `\r\n");
      out.write("			})\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 조회버튼\r\n");
      out.write("		document.querySelector('#searchbtn').addEventListener('click',(e)=>{\r\n");
      out.write("		    e.preventDefault()\r\n");
      out.write("		    if( document.querySelector('.indate1').value == '' || document.querySelector('.indate2').value == ''){\r\n");
      out.write("		    	alert(\"날짜값을 입력해야합니다.\")\r\n");
      out.write("		    } else {\r\n");
      out.write("		    	document.querySelector('#searchForm').submit();\r\n");
      out.write("		    }\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		const del = document.querySelectorAll('.tkr')\r\n");
      out.write("		const deleteF = document.querySelectorAll('.deleteForm')\r\n");
      out.write("		for(let i = 0; i < del.length; i++){\r\n");
      out.write("			del[i].addEventListener('click', (e)=>{\r\n");
      out.write("				e.preventDefault()\r\n");
      out.write("				const tt = confirm(\"정말로 삭제하시겠습니까?\")\r\n");
      out.write("				if(tt){\r\n");
      out.write("					deleteF[i].submit();\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		// 초기화버튼\r\n");
      out.write("	  	document.querySelector('#reset').addEventListener('click',(e)=>{\r\n");
      out.write("		    e.preventDefault()\r\n");
      out.write("		    document.querySelector('.wp3').value = '';\r\n");
      out.write("		    document.querySelector('.indate1').value = '';\r\n");
      out.write("		    document.querySelector('.indate2').value = '';\r\n");
      out.write("	 	})\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/qualityControl.jsp(52,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("dto");
    // /WEB-INF/qualityControl.jsp(52,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${resultList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<div class=\"dex item\" style=\"width: 99%;\">\r\n");
          out.write("							<div class=\"dateB\">\r\n");
          out.write("								");
          if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("								<!-- gpt 사용했음 fmt 라이브러리 공부해야함. -->\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"emdwp\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("							<div class=\"emdtn\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productionCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("							<div class=\"text1\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.performanceComment}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("							<div class=\"emdId\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("							<input type=\"hidden\" name=\"productid\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.productId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								class=\"productid\"> <input type=\"hidden\"\r\n");
          out.write("								name=\"performanceId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.performanceId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("								class=\"performId\">\r\n");
          out.write("							<div>\r\n");
          out.write("								<button class=\"selectItem\">선택</button>\r\n");
          out.write("							</div>\r\n");
          out.write("						</div>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/qualityControl.jsp(55,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.reportTime}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/qualityControl.jsp(55,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd HH:mm:ss");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/qualityControl.jsp(202,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("ttT");
    // /WEB-INF/qualityControl.jsp(202,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ result }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<form method=\"post\" action=\"qualityControl\"\r\n");
          out.write("						class=\"dex item deleteForm\" style=\"width: 98%;\">\r\n");
          out.write("						<input type=\"hidden\" name=\"command\" value=\"delete\"> <input\r\n");
          out.write("							type=\"hidden\" id=\"qualityControlId\" name=\"qualityControlId\"\r\n");
          out.write("							value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ ttT.qualityControlId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("						<div class=\"dateB\" id=\"qualitydate\">\r\n");
          out.write("							");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("						</div>\r\n");
          out.write("						<div class=\"emdwp\" id=\"qualityName\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ttT.productNameST}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("						<div class=\"emdgkq\" id=\"qualityResult\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ttT.result}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("						<div class=\"tkdb\" id=\"qualityFailreason\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ttT.failreason}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("						<div class=\"text1\" id=\"qualityComments\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ttT.comments}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("						<div class=\"text1\" id=\"qualityUserId\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ttT.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("						<div\r\n");
          out.write("							style=\"display: flex; justify-content: center; align-items: center;\">\r\n");
          out.write("							<button style=\"font-size: 12px; height: 25px;\" class=\"modify\">수정</button>\r\n");
          out.write("							<input type=\"submit\" name=\"tn\" value=\"삭제\" class=\"tkr\"\r\n");
          out.write("								style=\"font-size: 12px; height: 25px;\">\r\n");
          out.write("\r\n");
          out.write("						</div>\r\n");
          out.write("					</form>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /WEB-INF/qualityControl.jsp(209,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ttT.reportTime}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/qualityControl.jsp(209,7) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd HH:mm:ss");
    int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
    return false;
  }
}
